### ISSUE TITLE
rTMS mode won't work

### ISSUE THREAD

**Issue by phivph** [nicolasmcnair/magpy#5]
Hello, I have managed to connect and control my lab's TMS using magpy. We have a Rapid2 stimulator (version 9+) with a Plus1 module connected. 
Single pulse mode works perfectly fine but as soon as I try to enable rTMS mode it crashes. No error message is given, but as soon as <myTMS.rTMSMode(enable=True, receipt=True)> the script would just crash.
I have also tried enabling rTMS mode using the setDuration(1) function, but it crashes in the same way.
Any idea why this is happening?
Find the code below:

from magpy import magstim

if __name__ == '__main__':
    myTMS=magstim.Rapid('COM5', unlockCode='<our_TMS_code_here>')
    myTMS.connect()
    errorCode,parameterInfo = myTMS.getParameters()
    myTMS.rTMSMode(enable=True, receipt=True)
    myTMS.disconnect()

Please note that the following code works perfectly fine:

from magpy import magstim

if __name__ == '__main__':
    myTMS=magstim.Rapid('COM5', unlockCode='<our_TMS_code_here>')
    myTMS.connect()
    x=myTMS.getParameters()
    print(x)
    myTMS.disconnect()

On the contrary, this would crash:

from magpy import magstim

if __name__ == '__main__':
    myTMS=magstim.Rapid('COM5', unlockCode='<our_TMS_code_here>')
    myTMS.connect()
    myTMS.rTMS(enable=True, receipt=True)
    x=myTMS.getParameters()
    print(x)
    myTMS.disconnect()

**Comment by nicolasmcnair** [comment]
Hey, sorry for the late reply. Will look into this as soon as I can.

**Comment by nicolasmcnair** [comment]
Is the code presented here copied directly from the scripts you're trying to run?

**Comment by phivph** [comment]
Sort of, I just removed the unlocking code of our TMS for here, but have the actual code in my script.

**Comment by nicolasmcnair** [comment]
In terms of your code there are two things. First the lines with:
`if name == 'main':`
should have 'dunders' around the name:
`if __name__ == 'main':`
Second, in the example that you say crashes, this line:
`myTMS.rTMS(enable=True, receipt=True)`
should be:
`myTMS.rTMSMode(enable=True) #the receipt argument is not needed since you aren't catching the return`
After fixing those, all three sections of code worked for me - I could enable rTMS mode and change the various parameters just fine. See if adjusting those things helps at all, otherwise I'll send you some code to try when I'm in tomorrow (working from home today).
 
Also, although this isn't related to the error you're getting, I recommend re-downloading magpy - as I just fixed a weird bug that pops up every now and again that can cause the magstim to disarm after arming it.

**Comment by nicolasmcnair** [comment]
Ahhh, I see what might have happened there. Because it's not in code, markdown converted your dunders to bold instead. Sorry! Ignore that comment. In that case, I'll send you some code to try tomorrow that should hopefully help us figure this out.

**Comment by phivph** [comment]
Hey thanks for the response. It still crashes even if I don’t use the receipt argument (tried it with True, False, and by not using it all).
I will re download MagPy as soon as I have access to the TMS again.
Looking forward to the code you’ll be sending tomorrow.

**Comment by nicolasmcnair** [comment]
Apologies, had an extremely busy time today, so will have to send tomorrow now. Sorry for the delay.

**Comment by phivph** [comment]
Understandable! No worries.

**Comment by nicolasmcnair** [comment]
Ok, I have a debug version of magstim.py here that will print out the commands that are sent to and received from the serialPortController. It will also write two text files: serial_log.txt which contains what the serialPortController sent to the magstim and what it received back; and robot_log.txt which logs the process maintaining the connection to the Magstim. Just rename it to magstim.py and replace the original. Then give the script test_rapid_commands.py a try. It should set the Magstim to fire a single 3s 10Hz train, and works perfectly on my SuperRapid. If you could send me the two files it creates hopefully we should be able to sort out what is happening.

[Testing.zip](https://github.com/nicolasmcnair/magpy/files/5376273/Testing.zip)

**Comment by phivph** [comment]
Thank you for this. Things are a bit complicated with the COVID situation but I should have access to the TMS tomorrow. I’ll run the test and send you the files ASAP.

**Comment by phivph** [comment]
I have run the scripts you have sent me and I am attaching the logs as well as the output from when I run the testing script.
In the compressed folder you will find: the serial and robot logs for running a single pulse script and the serial and robot logs for running an rtms script. Additionally you will find a txt file with the output I get when I run the test_rapid_commands.py.

Also, something I forgot to mention earlier is that I have been getting an error when the script was trying to switch the timer based on the platform. Therefore I directly import time from time with defaultTimer = time. I am not sure if this has anything to do with the above issue, but I hope that it helps.
[logs.zip](https://github.com/nicolasmcnair/magpy/files/5383889/logs.zip)

**Comment by nicolasmcnair** [comment]
One thing I missed before, but noticed now: In your script it has the line
`maggy = magstim.Rapid('COM5','1dbf-3cf2e555-16^')`
But the constructor for the Rapid is:
`def __init__(self, serialConnection, superRapid=DEFAULT_RAPID_TYPE, unlockCode=DEFAULT_UNLOCK_CODE, etc...`
So if you want to skip what type of super rapid you have (although you should probably include that too), you should use the following code. Note that I've omitted the final character in the unlock code '^' as this character (the CRC) is calculated automatically by MagPy:
`maggy = magstim.Rapid('COM5',unlockCode='1dbf-3cf2e555-16')`
Give that a try and see how you get on

Also, I haven't come across an error regarding switching the timer before (testing on Python 2 and 3 on Windows and Mac OSX). What OS and python version are you using? Having said that, I think I should update the toolbox to use perf_counter instead, as this will avoid the need to switch.

**Comment by phivph** [comment]
Hello again, sorry for the late response. I am running Python 3.8 on a Windows 10 (64-bit OS).
I have run the script again, including the super rapid type and without the CRC. Still crashes.
I am attaching the logs for this run below.

[logs (without CRC).zip](https://github.com/nicolasmcnair/magpy/files/5397339/logs.without.CRC.zip)

**Comment by nicolasmcnair** [comment]
OK, I think I've found the issue. Give this one a try.
[magstim_debug.zip](https://github.com/nicolasmcnair/magpy/files/5398348/magstim_debug.zip)

**Comment by nicolasmcnair** [comment]
Sorry, missed one fix. Try this instead.
[magstim_debug.zip](https://github.com/nicolasmcnair/magpy/files/5398362/magstim_debug.zip)

**Comment by phivph** [comment]
It seems we are getting close. I tested the new version you sent and I manage to connect and fire an rTMS sequence. However, here is what I noticed:
1. The test script you sent me will run without crashing, but the TMS will not fire.
2. Below you will see the code I used to finally trigger rTMS. However, if I don't use the the lines x=myTMS.getParameters(), print(x), the TMS for some reason will not fire the rTMS sequence but a single pulse.
3. I am attaching the new logs.

code that works:

`from magpy import magstim


if __name__ == '__main__':
    myTMS=magstim.Rapid('COM5', superRapid=2, unlockCode='1dbf-3cf2e555-16')
    myTMS.connect()
    errorCode,parameterInfo = myTMS.getParameters()
    myTMS.rTMSMode(enable=True)
    myTMS.setPower(50)
    myTMS.setFrequency(10)
    myTMS.setNPulses(30)
    myTMS.setDuration(10)
    myTMS.validateSequence()
    myTMS.arm(delay=(True))
    myTMS.ignoreCoilSafetySwitch()
    myTMS.fire()
    x=myTMS.getParameters()
    print(x)
    myTMS.disconnect()`


On the contrary, this would fire a single pulse:

`from magpy import magstim


if __name__ == '__main__':
    myTMS=magstim.Rapid('COM5', superRapid=2, unlockCode='1dbf-3cf2e555-16')
    myTMS.connect()
    errorCode,parameterInfo = myTMS.getParameters()
    myTMS.rTMSMode(enable=True)
    myTMS.setPower(50)
    myTMS.setFrequency(10)
    myTMS.setNPulses(30)
    myTMS.setDuration(10)
    myTMS.validateSequence()
    myTMS.arm(delay=(True))
    myTMS.ignoreCoilSafetySwitch()
    myTMS.fire()
    myTMS.disconnect()`


[logs_rTMS_works.zip](https://github.com/nicolasmcnair/magpy/files/5400433/logs_rTMS_works.zip)

**Comment by nicolasmcnair** [comment]
That's peculiar. Are those logs from the version that worked or the one that didn't? In either case, could you also attach the logs from the other version too? Thanks!

**Comment by phivph** [comment]
Below you will find all the log files. Ignore the previous zip folder and find all 3 sets below:

1. 1 set where rTMS works (see rTMS_works logs)
2. 1 set where rTMS produces a single pulse instead (spTMS logs)
3. 1 set where I run the test_script. Turing the test script, no pulses are produced but the script runs without crashing or producing erros.


[logs.zip](https://github.com/nicolasmcnair/magpy/files/5400896/logs.zip)

**Comment by nicolasmcnair** [comment]
OK, I think there were two things happening. I think the reason it might not be firing at all is I'm so used to using an air-cooled coil I forgot to call ignoreCoilSafetySwitch() - as the air-cooled coil doesn't have one. I've added that now to the test code. Also, when I added a check to MagPy on what the maximum frequency allowed by the machine is, I forgot to account for the fact that frequency is expressed (internally) as tenths of a Hertz. Fixed this now in the attached version and on github too.

[rTMS.zip](https://github.com/nicolasmcnair/magpy/files/5405925/rTMS.zip)

**Comment by phivph** [comment]
I tried the attached version. Your test script works perfectly fine and it produces the rTMS train perfectly fine.
However the script I wrote which I used before (and I am copying once again below) only produces a single pulse now. I am once again attaching the logs from your script which works (named test_) and my script, which give a single pulse.

`from magpy import magstim


if __name__ == '__main__':
    myTMS=magstim.Rapid('COM5', superRapid=2, unlockCode='1dbf-3cf2e555-16')
    myTMS.connect()
    errorCode,parameterInfo = myTMS.getParameters()
    myTMS.rTMSMode(enable=True)
    myTMS.setPower(60)
    myTMS.setFrequency(10)
    myTMS.setNPulses(30)
    myTMS.setDuration(3)
    myTMS.validateSequence()
    myTMS.arm(delay=(True))
    myTMS.ignoreCoilSafetySwitch()
    myTMS.fire()
    x=myTMS.getParameters()
    print(x)
    myTMS.disconnect()
    
`

[logs.zip](https://github.com/nicolasmcnair/magpy/files/5415948/logs.zip)

**Comment by nicolasmcnair** [comment]
So what's happening here is that your code is working, you're just disarming the coil (through myTMS.disconnect()) immediately after you start firing. So only one pulse in the train happens. If you import sleep at the top of your script:

`from time import sleep`

And then change the code at the end from:

```
myTMS.fire()
x=myTMS.getParameters()
print(x)
myTMS.disconnect()
```

to:

```
myTMS.fire()
sleep(3.1)
myTMS.disconnect()
```

You should get the full train.

**Comment by phivph** [comment]
Just tested it now. You were right, works perfectly fine! 
I also uninstalled the debug version and install the latest one and it also works like a charm.
You have been very helpful. I really appreciate your help and all the hard work you put in this!

**Comment by nicolasmcnair** [comment]
No problem. It has been a big help spotting and fixing some bugs that had crept in.
